version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - .:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

    command: npm start

