version: "3.9"

services:
  db:
    container_name: app
    image: postgres:12-alpine
#    environment:
#      POSTGRES_USER: "inventory_app"
#      POSTGRES_PASSWORD: "inventory123"
#      POSTGRES_DB: "inventory_app"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  backend:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#    env_file:
#      - .env
    depends_on:
      - db

volumes:
  postgres_data:

